namespace SpriteKind {
    export const title = SpriteKind.create()
}
function walkanim2 () {
    animation.runImageAnimation(
    mySprite,
    [img`
        .................
        .....fffff.......
        ....f2d222ff.....
        ....f1d4ee22f....
        ...ffffffee2ef...
        ..fffffffffeeef..
        .....4f4f4fffdf..
        ...eedfdfd4fdedf.
        ..edddddddffde4f.
        ..e44444fddfd4ff.
        ...fffffffd44ff..
        ....ffff4444ef...
        ......8eeeeeee...
        .....8996e2eee...
        ..ff81911e111ef..
        .ffdf19116e11eef.
        .ffef89666e11eef.
        ..ffef86666ee8ef.
        ..ffef.8888.fdef.
        ...ff........ff..
        `,img`
        .....fffff.......
        ....f2d222ff.....
        ....f1d4ee22f....
        ...ffffffee2ef...
        ..fffffffffeeef..
        .....4f4f4fffdf..
        ...eedfdfd4fdedf.
        ..edddddddffde4f.
        ..e44444fddfd4ff.
        ...fffffffd44ff..
        ....ffff444eef...
        ......8eeeeef....
        .....899662eef...
        ....819116eeef...
        ....81911e111e...
        ....899666e11e...
        .....86866e11e...
        ......fefeeee....
        .....fdfdeeef....
        .....ffffffff....
        `],
    100,
    true
    )
}
function runanim () {
    animation.runImageAnimation(
    mySprite,
    [img`
        .................
        .......fffff.....
        .....ff222d2f....
        ....f22ee4d1f....
        ...fe2eeffffff...
        ..feeefffffffff..
        ..fdfff4f4f4.....
        .fdedf4dfdfdee...
        .f4edffddddddde..
        .ff4dfddf44444e..
        ..ff44dfffffff...
        eeeeee444ffff....
        e111e2eeee8......
        .e11e2266998.....
        ..feee6611918ff..
        .fee66661191fdff.
        .fee66666698feff.
        .fe88866668feff..
        .fedf.8888.feff..
        ..ff........ff...
        `,img`
        .................
        .......fffff.....
        .....ff222d2f....
        ....f22ee4d1f....
        ...fe2eeffffff...
        ..feeefffffffff..
        ..fdfff4f4f4.....
        .fdedf4dfdfdee...
        .f4edffddddddde..
        .ff4dfddf44444e..
        ..ff44dfffffff...
        eeeeee444ffff....
        e111e2eeee8......
        .e11e2266998.....
        ..eeee6611918....
        ...8666611918....
        ...8666666998....
        ...886666868.....
        ....eeeefef......
        ....feeedfdf.....
        `],
    100,
    true
    )
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (gamestart == 1) {
        if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
            mySprite.setVelocity(0, -270)
        }
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    if (gamestart == 1) {
        direction = 0
        walkanim2()
    }
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    if (gamestart == 1) {
        direction = 1
        walkanim()
    }
})
function walkanim () {
    animation.runImageAnimation(
    mySprite,
    [img`
        .................
        .......fffff.....
        .....ff222d2f....
        ....f22ee4d1f....
        ...fe2eeffffff...
        ..feeefffffffff..
        ..fdfff4f4f4.....
        .fdedf4dfdfdee...
        .f4edffddddddde..
        .ff4dfddf44444e..
        ..ff44dfffffff...
        ...fe4444ffff....
        ...eeeeeee8......
        ...eee2e6998.....
        ..fe111e11918ff..
        .fee11e61191fdff.
        .fee11e66698feff.
        .fe8ee66668feff..
        .fedf.8888.feff..
        ..ff........ff...
        `,img`
        .......fffff.....
        .....ff222d2f....
        ....f22ee4d1f....
        ...fe2eeffffff...
        ..feeefffffffff..
        ..fdfff4f4f4.....
        .fdedf4dfdfdee...
        .f4edffddddddde..
        .ff4dfddf44444e..
        ..ff44dfffffff...
        ...fee444ffff....
        ....feeeee8......
        ...fee266998.....
        ...feee611918....
        ...e111e11918....
        ...e11e666998....
        ...e11e66868.....
        ....eeeefef......
        ....feeedfdf.....
        ....ffffffff.....
        `],
    100,
    true
    )
}
function runanim2 () {
    animation.runImageAnimation(
    mySprite,
    [img`
        .................
        .....fffff.......
        ....f2d222ff.....
        ....f1d4ee22f....
        ...ffffffee2ef...
        ..fffffffffeeef..
        .....4f4f4fffdf..
        ...eedfdfd4fdedf.
        ..edddddddffde4f.
        ..e44444fddfd4ff.
        ...fffffffd44ff..
        ....ffff444eeeeee
        ......8eeee2e111e
        .....8996622e11e.
        ..ff8191166eeef..
        .ffdf19116666eef.
        .ffef89666666eef.
        ..ffef86666888ef.
        ..ffef.8888.fdef.
        ...ff........ff..
        `,img`
        .................
        .....fffff.......
        ....f2d222ff.....
        ....f1d4ee22f....
        ...ffffffee2ef...
        ..fffffffffeeef..
        .....4f4f4fffdf..
        ...eedfdfd4fdedf.
        ..edddddddffde4f.
        ..e44444fddfd4ff.
        ...fffffffd44ff..
        ....ffff444eeeeee
        ......8eeee2e111e
        .....8996622e11e.
        ....8191166eeee..
        ....8191166668...
        ....8996666668...
        .....868666688...
        ......fefeeee....
        .....fdfdeeef....
        `],
    100,
    true
    )
}
let mySprite: Sprite = null
let direction = 0
let gamestart = 0
gamestart = 0
let mySprite2 = sprites.create(assets.image`title`, SpriteKind.title)
direction = 1
namespace userconfig {
    export const ARCADE_SCREEN_WIDTH = 256
    export const ARCADE_SCREEN_HEIGHT = 224
}
pauseUntil(() => controller.anyButton.isPressed())
sprites.destroy(mySprite2)
pause(500)
gamestart = 1
scroller.setLayerImage(scroller.BackgroundLayer.Layer0, assets.image`myImage2`)
scroller.setLayerImage(scroller.BackgroundLayer.Layer4, assets.image`myImage0`)
scroller.scrollBackgroundWithSpeed(-5, 0, scroller.BackgroundLayer.Layer0)
scroller.setBackgroundScrollOffset(0, -200, scroller.BackgroundLayer.Layer0)
mySprite = sprites.create(img`
    .......fffff....
    .....ff222d2f...
    ....f22ee4d1f...
    ...fe2eeffffff..
    ..feeefffffffff.
    ..fdfff4f4f4....
    .fdedf4dfdfdee..
    .f4edffddddddde.
    .ff4dfddf44444e.
    ..ff44dfffffff..
    ...fee444ffff...
    ....feeeee8.....
    ...fee266998....
    ...feee611918...
    ...e111e11918...
    ...e11e666998...
    ...e11e66868....
    ....eeeefef.....
    ....feeedfdf....
    ....ffffffff....
    `, SpriteKind.Player)
mySprite.x = 25
mySprite.y = 200
tiles.setCurrentTilemap(tilemap`level1`)
mySprite.ay = 500
scene.cameraFollowSprite(mySprite)
game.onUpdate(function () {
    if (gamestart == 1) {
        if (mySprite.vy < 0) {
            if (direction == 1) {
                mySprite.setImage(img`
                    ............ee..
                    ...........e11e.
                    ..........e1111e
                    .......fffff111e
                    .....ff222d2f1e.
                    ....f22ee4d1fef.
                    ...fe2eeffffff..
                    ..feeefffffffff.
                    ..fdfff4f4f4ef..
                    .fdedf4dfdfdee..
                    .f4edffddddddde.
                    .ff4dfddf44444e.
                    ..ff44dfffffff..
                    .eeeee444ffff...
                    ee11eeeeee8.....
                    e1111e266998....
                    e1111e6611918ff.
                    .e11e6661191fdff
                    .fee66666698feff
                    .fe88866668feff.
                    .fedf.8888.feff.
                    ..ff........ff..
                    `)
            } else {
                if (direction == 0) {
                    mySprite.setImage(img`
                        ..ee............
                        .e11e...........
                        e1111e..........
                        e111fffff.......
                        .e1f2d222ff.....
                        .fef1d4ee22f....
                        ..ffffffee2ef...
                        .fffffffffeeef..
                        ..fe4f4f4fffdf..
                        ..eedfdfd4fdedf.
                        .edddddddffde4f.
                        .e44444fddfd4ff.
                        ..fffffffd44ff..
                        ...ffff444eeeee.
                        .....8eeeeee11ee
                        ....899662e1111e
                        .ff8191166e1111e
                        ffdf1911666e11e.
                        ffef89666666eef.
                        .ffef86666888ef.
                        .ffef.8888.fdef.
                        ..ff........ff..
                        `)
                }
            }
        }
        if (mySprite.vy > 0) {
            if (direction == 1) {
                mySprite.setImage(img`
                    .......fffff....
                    .....ff222d2f...
                    ....f22ee4d1f...
                    ...fe2eeffffff..
                    ..feeefffffffff.
                    ..fefffff4ff....
                    .feeff4ddddd....
                    .fedffddfdfd....
                    .fdedfddfdfdee..
                    .f4edffddddddde.
                    ..f4dfddf44444e.
                    .e11e4dfffffff1e
                    e1111e444ffff11e
                    e1111eeeee8e1ff.
                    .e11e2266998fdff
                    .fee86661191feff
                    .fee86661191feff
                    .fed88666698feff
                    ..ff.886668..ff.
                    ......8888......
                    `)
            } else {
                if (direction == 0) {
                    mySprite.setImage(img`
                        ....fffff.......
                        ...f2d222ff.....
                        ...f1d4ee22f....
                        ..ffffffee2ef...
                        .fffffffffeeef..
                        ....ff4fffffef..
                        ....ddddd4ffeef.
                        ....dfdfddffdef.
                        ..eedfdfddfdedf.
                        .edddddddffde4f.
                        .e44444fddfd4f..
                        e1fffffffd4e11e.
                        e11ffff444e1111e
                        .ff1e8eeeee1111e
                        ffdf8996622e11e.
                        ffef19116668eef.
                        ffef19116668eef.
                        ffef89666688def.
                        .ff..866688.ff..
                        ......8888......
                        `)
                }
            }
        }
        if (!(controller.left.isPressed() || controller.right.isPressed() || (mySprite.vy < 0 || mySprite.vy > 0))) {
            if (direction == 1) {
                mySprite.setImage(img`
                    .......fffff....
                    .....ff222d2f...
                    ....f22ee4d1f...
                    ...fe2eeffffff..
                    ..feeefffffffff.
                    ..fdfff4f4f4....
                    .fdedf4dfdfdee..
                    .f4edffddddddde.
                    .ff4dfddf44444e.
                    ..ff44dfffffff..
                    ...fee444ffff...
                    ....feeeee8.....
                    ...fee266998....
                    ...feee611918...
                    ...e111e11918...
                    ...e11e666998...
                    ...e11e66868....
                    ....eeeefef.....
                    ....feeedfdf....
                    ....ffffffff....
                    `)
            } else {
                if (direction == 0) {
                    mySprite.setImage(img`
                        ....fffff.......
                        ...f2d222ff.....
                        ...f1d4ee22f....
                        ..ffffffee2ef...
                        .fffffffffeeef..
                        ....4f4f4fffdf..
                        ..eedfdfd4fdedf.
                        .edddddddffde4f.
                        .e44444fddfd4ff.
                        ..fffffffd44ff..
                        ...ffff444eef...
                        .....8eeeeef....
                        ....899662eef...
                        ...819116eeef...
                        ...81911e111e...
                        ...899666e11e...
                        ....86866e11e...
                        .....fefeeee....
                        ....fdfdeeef....
                        ....ffffffff....
                        `)
                }
            }
        }
    }
})
game.onUpdate(function () {
    if (gamestart == 1) {
        if (controller.B.isPressed()) {
            if (controller.left.isPressed()) {
                mySprite.vx += -40
            } else {
                if (controller.right.isPressed()) {
                    mySprite.vx += 40
                }
            }
        } else {
            if (controller.left.isPressed()) {
                mySprite.vx += -30
            } else {
                if (controller.right.isPressed()) {
                    mySprite.vx += 30
                }
            }
        }
        mySprite.vx = mySprite.vx * 0.8
    }
})
